repos=(
batisteo.vscode-django
charliermarsh.ruff
csstools.postcss
deerawan.vscode-faker
devsense.composer-php-vscode
devsense.intelli-php-vscode
devsense.phptools-vscode
devsense.profiler-php-vscode
docker.docker
donjayamanne.python-environment-manager
donjayamanne.python-extension-pack
dsznajder.es7-react-js-snippets
eamodio.gitlens
eriklynd.json-tools
formulahendry.code-runner
fwcd.kotlin
kevinrose.vsc-python-indent
mathiasfrohlich.kotlin
ms-azuretools.vscode-containers
ms-azuretools.vscode-docker
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-python.vscode-python-envs
naco-siren.gradle-language
njpwerner.autodocstring
perkovec.emoji
pkief.material-icon-theme
redhat.java
redhat.vscode-yaml
sethjones.kotlin-on-vscode
shellomo.django-template-intelligence
tyriar.lorem-ipsum
vmware.vscode-boot-dev-pack
vmware.vscode-spring-boot
vscjava.vscode-gradle
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
vscjava.vscode-spring-boot-dashboard
vscjava.vscode-spring-initializr
wholroyd.jinja
xabikos.javascriptsnippets
zhuangtongfa.material-theme
)

for repo in "${repos[@]}"
do
	code --install-extension "$repo"
done
